# Generated by Django 4.2.7 on 2023-12-04 06:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=240, verbose_name='customerName')),
                ('contactDetails', models.CharField(max_length=240, verbose_name='ContactDetails')),
                ('string_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
