# Generated by Django 4.2.7 on 2023-12-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='AboutUs',
        ),
    ]
