# Generated by Django 4.2.7 on 2023-12-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_rename_customer_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='name',
            new_name='caption',
        ),
    ]
