# Generated by Django 4.2.7 on 2023-12-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_rename_name_aboutus_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='base64Image',
            field=models.CharField(max_length=10000, verbose_name='base64Image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='caption',
            field=models.CharField(max_length=10000, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='description'),
        ),
    ]
