# Generated by Django 5.0 on 2023-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0003_details_delete_detailsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='location_images/')),
                ('address', models.CharField(max_length=255)),
                ('overview', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
