# Generated by Django 5.0 on 2023-12-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0004_location_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='location_images/')),
                ('address', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
