# Generated by Django 5.0 on 2023-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0005_detailsapp_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsapp',
            name='image',
        ),
        migrations.AddField(
            model_name='detailsapp',
            name='review',
            field=models.CharField(default='YourDefaultValueHere', max_length=255),
        ),
    ]
