# Generated by Django 5.0 on 2023-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=240, verbose_name='customerName')),
                ('contactDetails', models.CharField(max_length=240, verbose_name='contactDetails')),
                ('selectedServices', models.CharField(max_length=240, verbose_name='selectedServices')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
